CLS
PRINT "PC DATA AQUITION"
PRINT ""
PRINT "TO EXIT PRESS CTRL+PAUSE"
INPUT "ENTER FILE NAME: "; N$
PRINT "TIME        DATA"
OPEN N$ FOR OUTPUT AS #2
PRINT #2, "LOGGING STARTED AT "; TIME$; " ON "; DATE$
PRINT #2, ""
CLOSE #2
LOOP1:
OPEN N$ FOR APPEND AS #2
OPEN "COM1:9600,N,8,1,CD0,CS0,DS0,OP0,RS,tb2048,rb2048" FOR INPUT AS #1
a$ = INPUT$(1, 1)
PRINT TIME$; "     "; a$
PRINT #2, TIME$; "    "; a$
CLOSE #1
CLOSE #2
GOTO LOOP1
END